@startuml database
class Study {
    Study-ID int not null, auto_increment
    --
    Creator-UID int not null -- Foreign Key(UserProfile)
    Studyname varchar(255)
    Starttime varchar(255)
    Endtime varchar(255)
    MBTI varchar(255) check (MBTI IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Subject varchar(255)
    StudyInfo5 varchar(255)
    StudyInfo6 varchar(255)
}

class StudyMember {
    Study-ID varchar(255) not null -- Foreign Key(Study)
    Participant-UID varchar(255) not null -- Foreign Key(UserProfile)
    --
    Creator tinyint(1) not null
}

class IdealMBTI {
    ID int not null, auto_increment
    --
    MBTI vachar(20) check (Ideal1 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal1 varchar(20) check (Ideal1 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal2 varchar(20) check (Ideal2 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal3 varchar(20) check (Ideal3 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal4 varchar(20) check (Ideal4 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal5 varchar(20) check (Ideal5 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal6 varchar(20) check (Ideal6 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal7 varchar(20) check (Ideal7 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal8 varchar(20) check (Ideal8 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal9 varchar(20) check (Ideal9 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal10 varchar(20) check (Ideal10 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal11 varchar(20) check (Ideal11 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal12 varchar(20) check (Ideal12 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal13 varchar(20) check (Ideal13 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal14 varchar(20) check (Ideal14 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal15 varchar(20) check (Ideal15 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
    Ideal16 varchar(20) check (Ideal16 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
}

@enduml

' create table Study (
'     StudyID int not null primary key auto_increment,
'     CreatorUID int not null,
'     Studyname varchar(255)
'     Starttime varchar(255),
'     Endtime varchar(255),
'     MBTI varchar(255) check (MBTI IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Subject varchar(255),
'     StudyInfo5 varchar(255),
'     StudyInfo6 varchar(255),
'     foreign key (CreatorUID) references UserProfile(uid) on delete cascade
' );

' create table StudyMember (
'     StudyID int not null,
'     ParticipantUID int not null,
'     Creator tinyint(1) not null,
'     foreign key (StudyID) references Study(StudyID) on delete cascade,
'     foreign key (ParticipantUID) references UserProfile(uid) on delete cascade
' );

' create table IdealMBTI (
'     ID int not null primary key auto_increment,
'     MBTI varchar(20) check (Ideal1 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal1 varchar(20) check (Ideal1 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal2 varchar(20) check (Ideal2 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal3 varchar(20) check (Ideal3 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal4 varchar(20) check (Ideal4 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')).
'     Ideal5 varchar(20) check (Ideal5 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal6 varchar(20) check (Ideal6 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal7 varchar(20) check (Ideal7 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal8 varchar(20) check (Ideal8 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal9 varchar(20) check (Ideal9 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal10 varchar(20) check (Ideal10 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal11 varchar(20) check (Ideal11 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal12 varchar(20) check (Ideal12 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal13 varchar(20) check (Ideal13 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal14 varchar(20) check (Ideal14 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal15 varchar(20) check (Ideal15 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP')),
'     Ideal16 varchar(20) check (Ideal16 IN('ENTJ', 'ENTP', 'INTJ', 'INTP', 'ESTJ', 'ESFJ', 'ISTJ', 'ISFJ', 'ENFJ', 'ENFP', 'INFJ', 'INFP', 'ESTP', 'ESFP', 'ISTP', 'ISFP'))
' );